-- AlterTable
ALTER TABLE "Investment"
  ADD COLUMN "investedAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN "purchaseDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "platform" TEXT,
  ADD COLUMN "notes" TEXT,
  ADD COLUMN "isAutoSync" BOOLEAN NOT NULL DEFAULT false;
